### ISSUE TITLE
convert to gh-pages

### ISSUE THREAD

**Issue by igalic** [voxpupuli/voxpupuli.github.io#17]
Can we please convert this repository to gh-pages :O
i'd really rather write Markdown, than HTML.

**Comment by igalic** [comment]
@danzilio hint hint hint :)

**Comment by danzilio** [comment]
Oh god I'm the GH pages guy now? ;)

**Comment by danzilio** [comment]
I can probably do this today! Markdown all the things!

**Comment by igalic** [comment]
\o/

**Comment by daenney** [comment]
Done.
