### ISSUE TITLE
style our site to be recognizable

### ISSUE THREAD

**Issue by igalic** [voxpupuli/voxpupuli.github.io#18]
the style of our site needs an overhaul that makes it actually recognizable.

i'm fine with throwing everything out the window and starting with a fresh design (*template* (so long as it isn't github's:))

This can happen before, or after #17.

**Comment by daenney** [comment]
Done. It currently uses Bootstrap + Material Design theme. We can easily change it to anything from there or even get an agency involved to help us create our own image.
