### ISSUE TITLE
access to this repo

### ISSUE THREAD

**Issue by ghoneycutt** [voxpupuli/voxpupuli.github.io#197]
Seems I am missing maintainer access to this repo.

**Comment by ghoneycutt** [comment]
@bastelfreak @alexjfisher help :)

**Comment by bastelfreak** [comment]
At the moment all collaborators have write acces. Are you missing a specific permission?
![2019-08-04-111514_761x212_scrot](https://user-images.githubusercontent.com/341866/62421863-47b0ad00-b6a9-11e9-83a3-ebc99cc76234.png)

We require signed commits and up-to-date branches for a merge.

**Comment by ghoneycutt** [comment]
Thanks for adding me!
