### ISSUE TITLE
allow sub-sites to reuse our main-site's style

### ISSUE THREAD

**Issue by igalic** [voxpupuli/voxpupuli.github.io#54]
…by exposing it in CSS, and simply allowing them to include it.

This might be a step we wanna take after having a representable style on the main site ;)

**Comment by daenney** [comment]
Why? It's just bootstrap + material design theme. They can already include things and make it look identical.

**Comment by igalic** [comment]
@daenney would you mind doing that in our logos/ repo, please?

**Comment by daenney** [comment]
I'm not sure I understand, what do you want me to do?

**Comment by igalic** [comment]
could you try to make it so that https://voxpupuli.org/logos/ doesn't look like unstyled html?

**Comment by daenney** [comment]
Oooh. I see.

**Comment by daenney** [comment]
Done: https://github.com/voxpupuli/logos/commit/0d47b24ce67964ffe21ec39f6f3e103d9ae2845f
