### ISSUE TITLE
"Project maintainers" link in COC is broken

### ISSUE THREAD

**Issue by 3flex** [voxpupuli/voxpupuli.github.io#59]
The link leads to a 404 error at https://github.com/orgs/voxpupuli/teams/project-maintainers

**Comment by daenney** [comment]
Hmm, it works for me and it's a public team too. Are teams not visible to members outside of the org?

**Comment by 3flex** [comment]
Not sure... while logged in to Github, I get a 404 error. When logged out, I see a Github login page.

When I'm logged in:
![image](https://cloud.githubusercontent.com/assets/170028/17366703/8b34b616-595a-11e6-999c-fd7220a400c7.png)

Logged out:
![image](https://cloud.githubusercontent.com/assets/170028/17366719/a7828514-595a-11e6-9229-527550103dd9.png)

**Comment by igalic** [comment]
it would appear that's the case

**Comment by rnelson0** [comment]
@daenney Confirmed, that page is not available to external users. https://github.com/orgs/voxpupuli/people is the publicly accessible page, though I am not certain that fits the intent of the original link.

**Comment by daenney** [comment]
Ah. In that case we need to specifically enumerate people in the README. I'm a bit disappointed that public teams aren't "public" in that sense, but only visible to members within the org.

**Comment by igalic** [comment]
which brings us back to our favourite https://github.com/voxpupuli/plumbing/pull/45

**Comment by nibalizer** [comment]
updated today!

**Comment by ryayon** [comment]
Issue still relevant

**Comment by JacobHenner** [comment]
Still relevant.
